# Spring Cloud 配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 223.82.75.76:8848
        username: lovelumine
        password: lovelumine47
        namespace: 4850addc-6018-4aea-b1aa-f5cb3f6e695d # prod
#        namespace: fba13bcb-89a6-40d0-8492-40e3eadc9a0e # dev

# BaiDuYun
baidu:
  accessKeyId: ALTAKgIm9DHzDPsRcLjVycygfT
  secretAccessKey: b9e34bc5c6a04204813857cfe7d8c3b2
  # SMS 服务
  sms:
    signatureId: sms-sign-HKpwwl39058
    template: sms-tmpl-btFhKG25676
    endpoint: http://smsv3.bj.baidubce.com

# AliPay
alipay:
  # APP ID
  appId: 9021000135635648
  # 应用私钥
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkctZ2X17TaNhtJIzZJowEH1BuRbXtcy7TLm6cAnloPRqpGBO1ndnccL7flWMl2xGy7zYmoBnEkqZa+GPY+TtRyjUu1ZcMaB5fsTniUqiUbDSuE0qzcbmblcPO7///iQz7kYAM9PDWlw/wIaqqb7/1yBMVGBhFlhiEHUQFbh9SMBHNy0reeE6A418HLrYfEc72bMS02YdJW5HJHcl6NzJS6QmzC+mm71NiJv3eVrQ+hUnH06oc0LeKoXisK/msRaxZOQgKFG+K6SqqyCSUj/AXzd43PXUpEuA4JORKAQUTnRPsjx0tYK4eZVZQMJHIG8dJeqgFnBd/fuQgI98rHfY9AgMBAAECggEAe4SKE2U062P/05K1fFFYr6v5lKolqNFwJUzl5aZyHFpxEPs1qp+CyPGiXHtvejqeg6DrMn3kfOKNsxyImqsw5BEWezQQ/U+jKMsMKDNfzgOsWefBnyDXgcYuyds4lG4TY015OcIst3HFld8julqve2Oo+ZoceP/xMCJvOgjp26dq1OTlZtFEjP6pXVqJSudfIIHPBWBObi2RCA3hQNGFS9M2GPHGqGbyTFc5GVWzZTssA7PigRhhEPIQqbH9EIkLiLrkIekHG9U35IgYzps3h05/ku4fvrCZgDtKAI5OCxuzm9JD74hyXGjoEhpqCtt8tWDkqP9OBMmzATALImNJoQKBgQDoHT1Lpfga+K0NYU/TSioddllPro6kmxAxQlrorPwMkPeIbnmLvpYoVY0cxJ7rvwXYyyJWAKSpDT+4gil6hSaByo7Nwprh+2VJzwUt29fWhJGFdNDW3izbwdK5MLhPztXgnqnrG3YPjimQt8TQZLga+4iVtmc2HCAd84uiv6v0CQKBgQC1XwgFw7pflxxfCMLAqqQ1yJv3Fe3WUQQt+9EoS8iqdwalVVGAbvvW7t3SrnTU+tfJvHM4x+w+iVkGq4W4P2HLzFOMwGIJJLa3OpbsWQ8a+1YQeVYkmr8y94f8/bAf0Qzf25d9RZfLh1QiW84nyBitZbWRQxWJSL6bWQdHGs7FlQKBgGTNFep9WEL2Tcjqwszif2muFNkq2F2Zza1mwK4dOZSHfEgumfBbQ0Ce7ppYtR9yJKrihLXOr7OOwmZxeGvx2SgyfFPVOIf9Mh6cngYtXA2YIs5PTcaSU+7XvJiaFODr1SwoG2iz01CsD1b+x6UsqFtncwh5X1c7XaNEOhbioF1pAoGABI7Z1cNAeMyEYwMGWe8v50YeXUxIyN0KXNl6PSgCZ/5LxXXqcW7Yl2MzYesOdpfDOoeo4aFsl3m+KgO/fYziOUvuQZhIHnC0wtAPIOtwDL6KQCm8d3kIGxDLcxkxBuurBikvmm9YTD4faCmkea12qUzoDjmAXg3c9Gx9WVUcIy0CgYEAsYxz5IcQ6JQuKpgg+Z0gx1atFbf3o32uoyQlVpUARYJmU4hYkYJ9j4kBqC5wacA/fNzlHUXqSoR7Op5AsZWbmPyRKXmK6KpKf4nszQON5FaqiRcpKV2bk9bFhHrZNupbTuoqbNuEgEi3AE76ZwQVsIIQ4yioIPlgB6CSbOe12Is=
  # 支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq69n08J2EelMloF9NukKylpQGi0fEN/E4RgkyFPCrr7omdaeQGAvzyIjcH4V5Q   AJYfvhR/1+NMNyuwBfMv2npqq83DYtchR9mQy7IAUfsAHhIhldS/IGcI3dE+WP2ywEfE4I97YLLooN4vVR4uygd0dEaIG8Ht2oGeiHY35y20f0B73zrHb2C82ZcLcplgjXACJqLw91E3nBUbMfSP8ZBCjvvz/oL56aEb1M+nUyN6VpWSqBjyulTecLcUEH4LeOf9q+s8u0/iRrtGesneu1aBuviSNdR+hYfyDLzRroieYmTfsUX7+AdAtakWtdplttZd1r4VPOmUPigwfhZeiRZQIDAQAB
  # 回调接口，支付后后端回调 url 接口
  notifyUrl: http://mingink.natapp1.cc/api/v1/order/notify/payMode/1
  # 返回路径，支付后前端跳转 url 链接
  returnUrl: http://zensheep.natapp1.cc/dashboard/workbench

# 微信支付
wx:
  pay:
    # APP ID
    appId:
    # APP密钥
    appSecret:
    # 微信支付商户号
    mchId:
    # 商户号密钥
    mchKey:
    # API密钥
    apiV3Key:
    # 商户号退款证书地址
    apiClientCert:
    # 商户API证书的证书序列号
    merchantSerialNumber:

# Gorse
gorse:
  endpoint: http://223.82.75.76:8088
  apiKey:

# swagger
## springdoc-openapi 项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

## knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false
  setting:
    language: zh_cn